from typing import Any, Dict, List, Optional
from schemas import BusinessType, ItemType, OrderType


CAPABILITIES: Dict[str, Dict[str, Any]] = {
    "restaurant": {
        "type": "restaurant",
        "productNoun": "dish",
        "productNounPlural": "dishes",
        "cartNoun": "order",
        "checkoutTitle": "Review Your Order",
        "checkoutCta": "Place Order",
        "checkoutBlockedLabel": "Select dining option to continue",
        "emptyCartTitle": "Your tray is empty",
        "addItemsLabel": "Add dishes to start",
        "confirmationTitle": "Order sent to kitchen",
        "confirmationMessage": "We've received your order. Please take your token receipt.",
        "customerNameLabel": "Name for callout",
        "customerNameHelper": "We'll announce this name when your food is ready.",
        "customerNamePlaceholder": "e.g. Alex",
        "tableLabel": "Table number",
        "notesLabel": "Kitchen instructions",
        "allowedOrderModes": ["dine_in", "takeaway"],
        "itemTypes": ["veg", "non_veg"],
        "supportedFilters": ["veg", "nonVeg", "spicy", "popular", "bestseller", "recommended", "combos", "discounted", "available", "priceSort"],
        "supportedTags": ["Chef Special", "Spicy", "Bestseller", "New", "Must Try", "Popular"],
        "variantTypes": ["Portion", "Spice Level", "Preparation"],
        "startScreenActions": [
            {"id": "dine_in", "title": "Dine In", "subtitle": "Enjoy your meal here", "orderType": "dine_in"},
            {"id": "takeaway", "title": "Takeaway", "subtitle": "Pack for pickup", "orderType": "takeaway"},
        ],
        "serviceBookingEnabled": False,
        "kitchenEnabled": True,
        "inventoryEnabled": True,
        "appointmentEnabled": False,
        "paymentEnabled": True,
        "showFoodTypeBadges": True,
        "orderModeLabel": "Dining preference",
    },
    "cafe": {
        "type": "cafe",
        "productNoun": "item",
        "productNounPlural": "items",
        "cartNoun": "tray",
        "checkoutTitle": "Your Cafe Order",
        "checkoutCta": "Brew It",
        "checkoutBlockedLabel": "Select pickup mode to continue",
        "emptyCartTitle": "Your tray is empty",
        "addItemsLabel": "Pick a beverage or treat",
        "confirmationTitle": "Order placed",
        "confirmationMessage": "Your drink is in the queue. Watch the counter screen.",
        "customerNameLabel": "Cup name",
        "customerNameHelper": "Printed on your cup label.",
        "customerNamePlaceholder": "Name for the cup",
        "tableLabel": "Table / Seat",
        "notesLabel": "Barista notes",
        "allowedOrderModes": ["dine_in", "takeaway"],
        "itemTypes": ["veg", "non_veg", "other"],
        "supportedFilters": ["hot", "iced", "milkBased", "nonCoffee", "veg", "popular", "new", "deals", "discounted", "available", "priceSort"],
        "supportedTags": ["Hot", "Iced", "Signature Roast", "Seasonal", "Popular", "Dairy Free"],
        "variantTypes": ["Cup Size", "Bean Blend", "Milk Choice", "Sweetness"],
        "startScreenActions": [
            {"id": "order_now", "title": "Order Now", "subtitle": "Coffee, drinks & bites", "orderType": "dine_in"},
            {"id": "takeaway", "title": "To Go", "subtitle": "Quick grab & run", "orderType": "takeaway"},
        ],
        "serviceBookingEnabled": False,
        "kitchenEnabled": True,
        "inventoryEnabled": True,
        "appointmentEnabled": False,
        "paymentEnabled": True,
        "showFoodTypeBadges": True,
        "orderModeLabel": "Order type",
    },
    "retail": {
        "type": "retail",
        "productNoun": "product",
        "productNounPlural": "products",
        "cartNoun": "bag",
        "checkoutTitle": "Self-Checkout",
        "checkoutCta": "Pay Now",
        "checkoutBlockedLabel": "Scan or select items to continue",
        "emptyCartTitle": "Your shopping bag is empty",
        "addItemsLabel": "Scan barcodes or tap products",
        "confirmationTitle": "Payment complete",
        "confirmationMessage": "Please collect your printed receipt and bag your items.",
        "customerNameLabel": "Customer name",
        "customerNameHelper": "Optional for receipt and warranty lookup.",
        "customerNamePlaceholder": "Optional name or phone",
        "tableLabel": "Bag / Locker #",
        "notesLabel": "Packing notes",
        "allowedOrderModes": ["pickup"],
        "itemTypes": ["retail"],
        "supportedFilters": ["popular", "new", "bestseller", "deals", "discounted", "available", "priceSort"],
        "supportedTags": ["Trending", "Limited Stock", "New Arrival", "Bestseller", "Sale"],
        "variantTypes": ["Size", "Color", "Material", "Pack"],
        "startScreenActions": [
            {"id": "self_checkout", "title": "Self-Checkout", "subtitle": "Scan or select & pay", "orderType": "pickup"},
        ],
        "serviceBookingEnabled": False,
        "kitchenEnabled": False,
        "inventoryEnabled": True,
        "appointmentEnabled": False,
        "paymentEnabled": True,
        "showFoodTypeBadges": False,
        "orderModeLabel": "Checkout",
    },
    "bakery": {
        "type": "bakery",
        "productNoun": "bake",
        "productNounPlural": "bakes",
        "cartNoun": "box",
        "checkoutTitle": "Bakery Box",
        "checkoutCta": "Box It Up",
        "checkoutBlockedLabel": "Select pack preference",
        "emptyCartTitle": "Box is empty",
        "addItemsLabel": "Add fresh bakes",
        "confirmationTitle": "Bakes reserved",
        "confirmationMessage": "Your box is being packed at the bakery counter.",
        "customerNameLabel": "Box label name",
        "customerNameHelper": "We'll label your box with this name.",
        "customerNamePlaceholder": "Customer name",
        "tableLabel": "Counter spot",
        "notesLabel": "Packaging instructions",
        "allowedOrderModes": ["takeaway", "dine_in"],
        "itemTypes": ["veg", "non_veg"],
        "supportedFilters": ["veg", "egg", "vegan", "popular", "new", "bestseller", "deals", "discounted", "available", "priceSort"],
        "supportedTags": ["Warm", "Eggless", "Fresh Out", "Artisanal", "Bestseller"],
        "variantTypes": ["Weight", "Piece Count", "Box Size"],
        "startScreenActions": [
            {"id": "box_to_go", "title": "Box to Go", "subtitle": "Pack for takeaway", "orderType": "takeaway"},
            {"id": "enjoy_here", "title": "Enjoy Here", "subtitle": "Bakery cafe seating", "orderType": "dine_in"},
        ],
        "serviceBookingEnabled": False,
        "kitchenEnabled": True,
        "inventoryEnabled": True,
        "appointmentEnabled": False,
        "paymentEnabled": True,
        "showFoodTypeBadges": True,
        "orderModeLabel": "Packaging type",
    },
    "pizza": {
        "type": "pizza",
        "productNoun": "pizza",
        "productNounPlural": "pizzas",
        "cartNoun": "order",
        "checkoutTitle": "Review Pizza Order",
        "checkoutCta": "Fire Up the Oven",
        "checkoutBlockedLabel": "Select crust & size",
        "emptyCartTitle": "No pizzas yet",
        "addItemsLabel": "Pick a signature pie",
        "confirmationTitle": "Pizzas in the oven!",
        "confirmationMessage": "We'll call your number when your crust is golden brown.",
        "customerNameLabel": "Order name",
        "customerNameHelper": "For order pickup callout.",
        "customerNamePlaceholder": "Name for callout",
        "tableLabel": "Table number",
        "notesLabel": "Baking instructions",
        "allowedOrderModes": ["dine_in", "takeaway"],
        "itemTypes": ["veg", "non_veg"],
        "supportedFilters": ["veg", "nonVeg", "spicy", "combos", "deals", "popular", "bestseller", "discounted", "available", "priceSort"],
        "supportedTags": ["Wood Fired", "Spicy", "Chef Special", "Loaded Cheese", "Bestseller"],
        "variantTypes": ["Crust", "Size", "Cheese Blend"],
        "startScreenActions": [
            {"id": "dine_in", "title": "Dine In", "subtitle": "Hot slice at your table", "orderType": "dine_in"},
            {"id": "takeaway", "title": "Takeaway Box", "subtitle": "Hot to take home", "orderType": "takeaway"},
        ],
        "serviceBookingEnabled": False,
        "kitchenEnabled": True,
        "inventoryEnabled": True,
        "appointmentEnabled": False,
        "paymentEnabled": True,
        "showFoodTypeBadges": True,
        "orderModeLabel": "Dining mode",
    },
    "burger": {
        "type": "burger",
        "productNoun": "burger",
        "productNounPlural": "burgers",
        "cartNoun": "combo tray",
        "checkoutTitle": "Complete Your Stack",
        "checkoutCta": "Grill It",
        "checkoutBlockedLabel": "Select meal options",
        "emptyCartTitle": "Tray is clear",
        "addItemsLabel": "Pick a burger or meal",
        "confirmationTitle": "Order sizzling!",
        "confirmationMessage": "Grilling your patties now. Keep your receipt handy.",
        "customerNameLabel": "Pickup name",
        "customerNameHelper": "Announced on the pickup speakers.",
        "customerNamePlaceholder": "Customer name",
        "tableLabel": "Table tent #",
        "notesLabel": "Grill instructions",
        "allowedOrderModes": ["dine_in", "takeaway"],
        "itemTypes": ["veg", "non_veg"],
        "supportedFilters": ["veg", "nonVeg", "spicy", "combos", "deals", "popular", "bestseller", "discounted", "available", "priceSort"],
        "supportedTags": ["Double Patty", "Smash", "Crispy", "Spicy", "Bestseller", "Meal Deal"],
        "variantTypes": ["Patty Count", "Bun Type", "Meal Upgrade"],
        "startScreenActions": [
            {"id": "eat_here", "title": "Eat Here", "subtitle": "Tray service", "orderType": "dine_in"},
            {"id": "takeaway", "title": "Take Out", "subtitle": "Bagged & ready", "orderType": "takeaway"},
        ],
        "serviceBookingEnabled": False,
        "kitchenEnabled": True,
        "inventoryEnabled": True,
        "appointmentEnabled": False,
        "paymentEnabled": True,
        "showFoodTypeBadges": True,
        "orderModeLabel": "Tray type",
    },
    "salon": {
        "type": "salon",
        "productNoun": "service",
        "productNounPlural": "services",
        "cartNoun": "booking",
        "checkoutTitle": "Confirm Your Appointment",
        "checkoutCta": "Book Appointment",
        "checkoutBlockedLabel": "Select customer name & stylist",
        "emptyCartTitle": "No services selected",
        "addItemsLabel": "Choose salon services",
        "confirmationTitle": "Booking confirmed",
        "confirmationMessage": "Your stylist will be ready for you shortly. Please take a seat.",
        "customerNameLabel": "Client name",
        "customerNameHelper": "Stylist will call you by this name.",
        "customerNamePlaceholder": "Your name",
        "tableLabel": "Station / Chair",
        "notesLabel": "Styling preferences",
        "allowedOrderModes": ["dine_in"],
        "itemTypes": ["service", "retail"],
        "supportedFilters": ["popular", "recommended", "new", "deals", "discounted", "available", "priceSort"],
        "supportedTags": ["Express", "Signature", "Organic", "Popular", "Consultation"],
        "variantTypes": ["Hair Length", "Stylist Level", "Add-on Treatment"],
        "startScreenActions": [
            {"id": "walk_in", "title": "Walk-in Service", "subtitle": "Check in & select services", "orderType": "dine_in"},
            {"id": "retail", "title": "Hair & Body Care", "subtitle": "Browse salon products", "orderType": "dine_in"},
        ],
        "serviceBookingEnabled": True,
        "kitchenEnabled": False,
        "inventoryEnabled": True,
        "appointmentEnabled": True,
        "paymentEnabled": True,
        "showFoodTypeBadges": False,
        "orderModeLabel": "Service mode",
    },
    "grocery": {
        "type": "grocery",
        "productNoun": "item",
        "productNounPlural": "items",
        "cartNoun": "basket",
        "checkoutTitle": "Express Checkout",
        "checkoutCta": "Pay & Bag",
        "checkoutBlockedLabel": "Scan items to continue",
        "emptyCartTitle": "Basket is empty",
        "addItemsLabel": "Scan or select items",
        "confirmationTitle": "Receipt ready",
        "confirmationMessage": "Payment verified. Please take your receipt and pack your bags.",
        "customerNameLabel": "Member name",
        "customerNameHelper": "For loyalty points and rewards.",
        "customerNamePlaceholder": "Name or Member ID",
        "tableLabel": "Lane number",
        "notesLabel": "Bagging preference",
        "allowedOrderModes": ["pickup"],
        "itemTypes": ["retail"],
        "supportedFilters": ["deals", "discounted", "popular", "available", "priceSort"],
        "supportedTags": ["Organic", "Farm Fresh", "Bulk Pack", "Offer", "Local"],
        "variantTypes": ["Weight", "Pack Size", "Flavor"],
        "startScreenActions": [
            {"id": "self_scan", "title": "Scan & Go", "subtitle": "Quick basket checkout", "orderType": "pickup"},
        ],
        "serviceBookingEnabled": False,
        "kitchenEnabled": False,
        "inventoryEnabled": True,
        "appointmentEnabled": False,
        "paymentEnabled": True,
        "showFoodTypeBadges": False,
        "orderModeLabel": "Checkout lane",
    },
    "ice_cream": {
        "type": "ice_cream",
        "productNoun": "scoop",
        "productNounPlural": "scoops",
        "cartNoun": "cup / cone",
        "checkoutTitle": "Your Sweet Treat",
        "checkoutCta": "Scoop It!",
        "checkoutBlockedLabel": "Pick your container",
        "emptyCartTitle": "Cup is empty",
        "addItemsLabel": "Choose your flavors",
        "confirmationTitle": "Scooping now!",
        "confirmationMessage": "Head to the pickup station to collect your treat.",
        "customerNameLabel": "Name",
        "customerNameHelper": "We'll call your name at the scoop counter.",
        "customerNamePlaceholder": "Name for callout",
        "tableLabel": "Seating",
        "notesLabel": "Allergy notes",
        "allowedOrderModes": ["dine_in", "takeaway"],
        "itemTypes": ["veg", "other"],
        "supportedFilters": ["vegan", "veg", "popular", "new", "deals", "discounted", "available", "priceSort"],
        "supportedTags": ["Dairy Free", "Seasonal", "Double Scoop", "Popular", "Kids Fav"],
        "variantTypes": ["Container (Cup/Waffle)", "Scoop Count", "Topping"],
        "startScreenActions": [
            {"id": "scoop_now", "title": "Scoop Here", "subtitle": "Enjoy in the parlor", "orderType": "dine_in"},
            {"id": "takeaway", "title": "Pack to Go", "subtitle": "Insulated tubs & pints", "orderType": "takeaway"},
        ],
        "serviceBookingEnabled": False,
        "kitchenEnabled": True,
        "inventoryEnabled": True,
        "appointmentEnabled": False,
        "paymentEnabled": True,
        "showFoodTypeBadges": True,
        "orderModeLabel": "Container preference",
    },
    "other": {
        "type": "other",
        "productNoun": "item",
        "productNounPlural": "items",
        "cartNoun": "cart",
        "checkoutTitle": "Review Selection",
        "checkoutCta": "Submit",
        "checkoutBlockedLabel": "Enter name to continue",
        "emptyCartTitle": "Nothing selected",
        "addItemsLabel": "Add items",
        "confirmationTitle": "Request received",
        "confirmationMessage": "Please head to the counter. Your request is being prepared.",
        "customerNameLabel": "Customer name",
        "customerNameHelper": "Staff will use this name to call you.",
        "customerNamePlaceholder": "Enter customer name",
        "tableLabel": "Reference",
        "notesLabel": "Notes",
        "allowedOrderModes": ["pickup"],
        "itemTypes": ["service", "retail", "other"],
        "supportedFilters": ["priceSort", "popular", "new", "deals", "discounted", "available"],
        "supportedTags": ["Popular", "New", "Featured", "Recommended", "Deal", "Discount"],
        "variantTypes": ["Option", "Package", "Add-on"],
        "startScreenActions": [
            {"id": "browse", "title": "Browse Items", "subtitle": "View available items", "orderType": "pickup"},
            {"id": "services", "title": "View Services", "subtitle": "Browse service options", "orderType": "pickup"},
        ],
        "serviceBookingEnabled": True,
        "kitchenEnabled": False,
        "inventoryEnabled": True,
        "appointmentEnabled": False,
        "paymentEnabled": True,
        "showFoodTypeBadges": False,
        "orderModeLabel": "Selection type",
    },
}


def get_capabilities(business_type: Optional[str | BusinessType] = None) -> Dict[str, Any]:
    raw_type = business_type.value if isinstance(business_type, BusinessType) else (business_type or "restaurant")
    return CAPABILITIES.get(raw_type, CAPABILITIES["restaurant"])


def get_item_type_options(business_type: Optional[str | BusinessType] = None) -> List[Dict[str, str]]:
    raw_type = business_type.value if isinstance(business_type, BusinessType) else (business_type or "restaurant")
    cap = get_capabilities(raw_type)
    labels = {
        "veg": "Veg pizza" if raw_type == "pizza" else "Veg burger" if raw_type == "burger" else "Cafe snack" if raw_type == "cafe" else "Ice cream" if raw_type == "ice_cream" else "Veg",
        "non_veg": "Non-veg pizza" if raw_type == "pizza" else "Non-veg burger" if raw_type == "burger" else "Non-veg snack" if raw_type == "cafe" else "Non-veg",
        "retail": "Retail product" if raw_type == "salon" else "Retail item",
        "service": "Service",
        "other": "Beverage / other" if raw_type == "cafe" else "Treat / other" if raw_type == "ice_cream" else "Other",
    }
    return [{"id": item_id, "label": labels.get(item_id, item_id.capitalize())} for item_id in cap.get("itemTypes", [])]
