"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState, type Dispatch, type ReactNode, type SetStateAction } from "react";
import { useBusiness } from "@/components/layout/BusinessProvider";
import { FilterBar, PageContainer, PageHeader, ResponsiveGrid, SectionHeader, Stack, Tabs, UnsavedChangesBar } from "@/components/layout/DashboardPrimitives";
import { Button, DataState, DataTable, DetailsDrawer, Input, MetricCard, SearchInput, Select, Skeleton, StatusPill } from "@/components/ui/DashboardUI";
import { api } from "@/lib/api";
import type { AdministrationActivity, AdministrationOverview, BusinessLocation, PaymentAccount, PaymentRecord, StaffMember, StaffRole } from "@/lib/types";

export type AdministrationMode = "overview" | "payments" | "locations" | "team" | "integrations" | "business-settings" | "activity-log";
type PageData = { overview: AdministrationOverview | null; accounts: PaymentAccount[]; payments: PaymentRecord[]; locations: BusinessLocation[]; staff: StaffMember[]; activity: AdministrationActivity[] };
const emptyData: PageData = { overview: null, accounts: [], payments: [], locations: [], staff: [], activity: [] };
const paymentTabs = ["Overview", "Providers", "Methods", "Location Assignments", "Terminals", "Rules", "Connection Activity"] as const;
const teamTabs = ["Members", "Invitations", "Roles & Permissions", "Security Policies", "Sessions"] as const;

export function AdministrationPage({ mode }: { mode: AdministrationMode }) {
  const { business, loading: businessLoading, error: businessError, refresh: refreshBusiness } = useBusiness();
  const [data, setData] = useState<PageData>(emptyData);
  const [loading, setLoading] = useState(true);
  const [refresh, setRefresh] = useState(0);

  useEffect(() => {
    if (!business?.id) return;
    let active = true;
    const loads: Promise<unknown>[] = [];
    if (mode === "overview") loads.push(api.administrationOverview(business.id));
    if (mode === "payments") { loads.push(api.paymentAccounts(business.id)); loads.push(api.payments(business.id)); loads.push(api.administrationActivity(business.id)); }
    if (mode === "locations") loads.push(api.administrationLocations(business.id));
    if (mode === "team") loads.push(api.staff(business.id));
    if (mode === "activity-log") loads.push(api.administrationActivity(business.id));
    if (mode === "integrations") loads.push(api.administrationActivity(business.id, "integration"));
    Promise.allSettled(loads).then((results) => {
      if (!active) return;
      const next = { ...emptyData }; let index = 0;
      const take = <T,>(apply: (value: T) => void) => { const result = results[index++]; if (result?.status === "fulfilled") apply(result.value as T); };
      if (mode === "overview") take<AdministrationOverview>((value) => { next.overview = value; next.activity = value.recent_activity; });
      if (mode === "payments") { take<{ accounts: PaymentAccount[] }>((value) => { next.accounts = value.accounts; }); take<{ payments: PaymentRecord[] }>((value) => { next.payments = value.payments; }); take<{ events: AdministrationActivity[] }>((value) => { next.activity = value.events; }); }
      if (mode === "locations") take<{ locations: BusinessLocation[] }>((value) => { next.locations = value.locations; });
      if (mode === "team") take<{ staff: StaffMember[] }>((value) => { next.staff = value.staff; });
      if (mode === "activity-log" || mode === "integrations") take<{ events: AdministrationActivity[] }>((value) => { next.activity = value.events; });
      setData(next); setLoading(false);
    });
    return () => { active = false; };
  }, [business?.id, mode, refresh]);

  const retry = () => { setLoading(true); setRefresh((value) => value + 1); };
  if (businessLoading) return <PageContainer width="wide"><Skeleton lines={8} label="Loading Administration" /></PageContainer>;
  if (businessError) return <PageContainer width="wide"><DataState kind="recoverable-error" title="Administration is unavailable" description={businessError} action={<Button variant="secondary" onClick={retry}>Retry</Button>} /></PageContainer>;
  if (!business) return <PageContainer width="compact"><DataState kind="permission-denied" title="No business selected" description="Choose a business before opening Administration." /></PageContainer>;
  if (loading) return <PageContainer width="wide"><Skeleton lines={8} label="Loading Administration" /></PageContainer>;
  // Individual sections render their own empty/error state; one unavailable endpoint must not blank the whole workspace.
  const props = { business, data, setData, onRefresh: retry, refreshBusiness };
  if (mode === "overview") return <Overview {...props} />;
  if (mode === "payments") return <Payments {...props} />;
  if (mode === "locations") return <Locations {...props} />;
  if (mode === "team") return <Team {...props} />;
  if (mode === "integrations") return <IntegrationsSafe {...props} />;
  if (mode === "business-settings") return <BusinessSettings {...props} />;
  return <ActivityLog {...props} />;
}

type AdminProps = { business: NonNullable<ReturnType<typeof useBusiness>["business"]>; data: PageData; setData: Dispatch<SetStateAction<PageData>>; onRefresh: () => void; refreshBusiness: () => Promise<unknown> };
function Header({ title, subtitle, onRefresh, actions }: { title: string; subtitle: string; onRefresh: () => void; actions?: ReactNode }) { return <PageHeader title={title} subtitle={subtitle} actions={<><Button variant="secondary" onClick={onRefresh}>Refresh</Button>{actions}</>} />; }
function date(value?: string | null) { return value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not recorded"; }
function status(value?: string | null): "success" | "warning" | "danger" | "info" | "neutral" { return value === "active" || value === "ready" || value === "open" || value === "connected" ? "success" : value === "attention" || value === "pending" || value === "temporarily_closed" ? "warning" : value === "inactive" || value === "error" || value === "disconnected" ? "danger" : "info"; }

function Overview({ business, data, onRefresh }: AdminProps) {
  const checks = data.overview?.checks || [];
  const links: Record<string, string> = { payments: "/dashboard/administration/payments", locations: "/dashboard/administration/locations", team: "/dashboard/administration/team", integrations: "/dashboard/administration/integrations", business_settings: "/dashboard/administration/business-settings" };
  return <PageContainer width="standard"><Header title="Administration" subtitle={`Business setup, access and configuration for ${business.name}.`} onRefresh={onRefresh} actions={<Link className="mt-button mt-button--primary" href="/dashboard/administration/business-settings">Business settings</Link>} /><PageSection title="Setup health"><ResponsiveGrid columns={3}>{checks.map((check) => <article className="mt-card mt-admin-card" key={check.key}><div className="mt-inline"><h2 className="mt-type-card-title">{label(check.key)}</h2><StatusPill status={status(check.status)}>{check.status}</StatusPill></div><p className="mt-type-card-description">{check.detail}</p>{links[check.key] && <Link className="mt-card-link" href={links[check.key]}>Open {label(check.key)}</Link>}</article>)}</ResponsiveGrid></PageSection><PageSection title="Needs attention"><ResponsiveGrid columns={2}>{checks.filter((check) => check.status === "attention").length ? checks.filter((check) => check.status === "attention").map((check) => <article className="mt-card" key={check.key}><SectionHeader title={label(check.key)} description={check.detail} actions={links[check.key] ? <Link className="mt-card-link" href={links[check.key]}>Resolve</Link> : undefined} /></article>) : <DataState kind="success" title="No administrative actions required" description="Real configuration checks are currently healthy." />}</ResponsiveGrid></PageSection><PageSection title="Recent administrative activity"><article className="mt-card"><ActivityTable rows={data.activity.slice(0, 10)} /><Link className="mt-card-link" href="/dashboard/administration/activity-log">Open Activity Log</Link></article></PageSection></PageContainer>;
}

function PageSection({ title, children }: { title: string; children: ReactNode }) { return <section className="mt-page-section"><SectionHeader title={title} />{children}</section>; }
function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (char) => char.toUpperCase()); }

function PaymentsLegacy({ business, data, setData, onRefresh }: AdminProps) {
  const [tab, setTab] = useState<(typeof paymentTabs)[number]>("Overview"); const [saving, setSaving] = useState("");
  const refreshAccount = async (provider: "stripe" | "razorpay" | "paytm") => { setSaving(provider); try { const next = await api.refreshPaymentAccount(business.id, provider); setData((current) => ({ ...current, accounts: current.accounts.map((account) => account.provider === provider ? next.account : account) })); } finally { setSaving(""); } };
  const setDefault = async (provider: "stripe" | "razorpay" | "paytm") => { setSaving(provider); try { const next = await api.updatePaymentAccount(business.id, provider, { is_default: true }); setData((current) => ({ ...current, accounts: current.accounts.map((account) => account.provider === provider ? next.account : { ...account, is_default: false }) })); } finally { setSaving(""); } };
  const content = tab === "Overview" ? <ResponsiveGrid columns={3}><MetricCard title="Connected providers" value={data.accounts.filter((account) => account.connection_status === "active" || account.connection_status === "connected").length} /><MetricCard title="Enabled methods" value={data.accounts.filter((account) => account.is_enabled).length} description="Provider-supported methods only." /><MetricCard title="Recent payments" value={data.payments.length} description="Transaction reporting remains in Sales & Reports." /></ResponsiveGrid> : tab === "Providers" ? <ResponsiveGrid columns={3}>{(["stripe", "razorpay", "paytm"] as const).map((provider) => { const account = data.accounts.find((item) => item.provider === provider); return <article className="mt-card mt-admin-card" key={provider}><SectionHeader title={label(provider)} description={account ? `${account.display_name || "Connected account"} · ${account.provider_account_id ? mask(account.provider_account_id) : "No account ID"}` : "Not connected"} /><StatusPill status={status(account?.connection_status)}>{account?.connection_status || "not connected"}</StatusPill><Stack gap={12}>{account ? <><Button variant="secondary" loading={saving === provider} onClick={() => refreshAccount(provider)}>Test connection</Button><Button variant="secondary" loading={saving === provider} disabled={account.is_default} onClick={() => setDefault(provider)}>Set default</Button></> : <DataState kind="empty" title="Connection required" description="Use the existing provider connection flow when credentials are available." />}</Stack></article>; })}</ResponsiveGrid> : tab === "Connection Activity" ? <article className="mt-card"><ActivityTable rows={data.activity.filter((event) => /payment|provider|webhook/i.test(`${event.action} ${event.entity || ""}`))} /></article> : <DataState kind="empty" title={`${tab} is not configured`} description={tab === "Location Assignments" ? "Payment provider location assignments are not present in the current payment contract." : `${tab} will appear when its backend contract is connected; no placeholder configuration is shown.`} />;
  return <PageContainer width="wide"><Header title="Payments" subtitle="Provider setup and connection health. Financial reporting remains in Sales & Reports." onRefresh={onRefresh} /><Tabs value={tab} tabs={paymentTabs.map((value) => ({ value, label: value }))} onChange={setTab} label="Payment sections" /><section className="mt-page-section">{content}</section></PageContainer>;
}

function Locations({ business, data, setData, onRefresh }: AdminProps) {
  const [search, setSearch] = useState(""); const [selected, setSelected] = useState<BusinessLocation | "new" | null>(null); const filtered = useMemo(() => data.locations.filter((item) => !search || `${item.name} ${item.city || ""}`.toLowerCase().includes(search.toLowerCase())), [data.locations, search]);
  return <PageContainer width="wide"><Header title="Locations" subtitle="First-class location settings inherit business defaults until overridden." onRefresh={onRefresh} actions={<Button onClick={() => setSelected("new")}>Add location</Button>} /><FilterBar><SearchInput label="Search locations" placeholder="Search locations" value={search} onChange={(event) => setSearch(event.target.value)} /><Select label="Status" defaultValue="all"><option value="all">All statuses</option><option value="open">Open</option><option value="temporarily_closed">Temporarily closed</option><option value="inactive">Inactive</option></Select></FilterBar><ResponsiveGrid columns={4} className="mt-admin-summary"><MetricCard title="Total" value={data.locations.length} /><MetricCard title="Active" value={data.locations.filter((item) => item.operating_status === "open").length} /><MetricCard title="Needs attention" value={data.locations.filter((item) => !item.address_line1 || !item.timezone).length} /><MetricCard title="Temporarily closed" value={data.locations.filter((item) => item.operating_status === "temporarily_closed").length} /></ResponsiveGrid><article className="mt-card"><DataTable caption="Business locations" rows={filtered} rowKey={(row) => row.id} emptyMessage={data.locations.length ? "No locations match the current filters." : "No locations are configured."} columns={[{ key: "name", header: "Location", cell: (row) => <button className="mt-table-link" onClick={() => setSelected(row)}>{row.name}</button> }, { key: "address", header: "Address", cell: (row) => row.address_line1 || "Missing" }, { key: "region", header: "Region", cell: (row) => [row.city, row.timezone].filter(Boolean).join(" · ") || "Uses business default" }, { key: "devices", header: "Devices", align: "end", cell: (row) => row.device_count || 0 }, { key: "status", header: "Status", cell: (row) => <StatusPill status={status(row.operating_status)}>{label(row.operating_status)}</StatusPill> }]} /></article>{selected && <LocationDrawer businessId={business.id} location={selected} onClose={() => setSelected(null)} onSaved={(location) => { setData((current) => ({ ...current, locations: current.locations.some((item) => item.id === location.id) ? current.locations.map((item) => item.id === location.id ? { ...item, ...location } : item) : [...current.locations, location] })); setSelected(location); }} onDeactivated={(id) => setData((current) => ({ ...current, locations: current.locations.map((item) => item.id === id ? { ...item, operating_status: "inactive" } : item) }))} />}</PageContainer>;
}

function LocationDrawer({ businessId, location, onClose, onSaved, onDeactivated }: { businessId: string; location: BusinessLocation | "new"; onClose: () => void; onSaved: (location: BusinessLocation) => void; onDeactivated: (id: string) => void }) {
  const current = location === "new" ? null : location; const [form, setForm] = useState({ name: current?.name || "", address_line1: current?.address_line1 || "", city: current?.city || "", country: current?.country || "", timezone: current?.timezone || "", currency_code: current?.currency_code || "" }); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const save = async () => { if (!form.name.trim()) { setError("Location name is required."); return; } setSaving(true); setError(""); try { const saved = current ? await api.updateAdministrationLocation(businessId, current.id, form) : await api.createAdministrationLocation(businessId, form); onSaved(saved); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save the location."); } finally { setSaving(false); } };
  const deactivate = async () => { if (!current || !window.confirm("Deactivate this location? It will remain available to records that reference it.")) return; const saved = await api.deactivateAdministrationLocation(businessId, current.id); onSaved(saved); onDeactivated(current.id); };
  const change = (key: keyof typeof form, nextValue: string) => setForm((currentForm) => ({ ...currentForm, [key]: nextValue }));
  return <DetailsDrawer open onClose={onClose} title={current ? current.name : "Add location"} confirmOnClose={JSON.stringify(form) !== JSON.stringify({ name: current?.name || "", address_line1: current?.address_line1 || "", city: current?.city || "", country: current?.country || "", timezone: current?.timezone || "", currency_code: current?.currency_code || "" }) ? "Discard unsaved location changes?" : undefined} footer={<><Button variant="secondary" onClick={onClose}>Close</Button><Button loading={saving} onClick={save}>Save location</Button></>}><Stack><Input label="Location name" value={form.name} onChange={(event) => change("name", event.target.value)} required /><Input label="Address" value={form.address_line1} onChange={(event) => change("address_line1", event.target.value)} /><Input label="City" value={form.city} onChange={(event) => change("city", event.target.value)} /><Input label="Country" value={form.country} onChange={(event) => change("country", event.target.value)} /><Input label="Timezone" placeholder="Uses business default when blank" value={form.timezone} onChange={(event) => change("timezone", event.target.value)} /><Input label="Currency" placeholder="Uses business default when blank" value={form.currency_code} onChange={(event) => change("currency_code", event.target.value.toUpperCase())} maxLength={3} />{error && <DataState kind="recoverable-error" title="Location not saved" description={error} />}{current && <><DataState kind="info" title="Inherited settings" description="Hours, ordering, payments, team and device assignment continue to use their current owners until dedicated location contracts are configured." /><Button variant="danger" onClick={deactivate} disabled={current.operating_status === "inactive"}>Deactivate location</Button></>}</Stack></DetailsDrawer>;
}

function TeamLegacy({ business, data, setData, onRefresh }: AdminProps) {
  const [tab, setTab] = useState<(typeof teamTabs)[number]>("Members"); const [invite, setInvite] = useState(false); const [selected, setSelected] = useState<StaffMember | null>(null);
  const content = tab === "Members" ? <article className="mt-card"><DataTable caption="Business team members" rows={data.staff} rowKey={(row) => row.id} emptyMessage="No team members have access." columns={[{ key: "name", header: "Member", cell: (row) => <button className="mt-table-link" onClick={() => setSelected(row)}>{row.full_name || row.email || "Unnamed member"}</button> }, { key: "email", header: "Email", cell: (row) => row.email || "Not available" }, { key: "role", header: "Role", cell: (row) => label(row.role) }, { key: "status", header: "Status", cell: () => <StatusPill status="success">Active</StatusPill> }]} /></article> : tab === "Roles & Permissions" ? <PermissionMatrix /> : <DataState kind="empty" title={`${tab} is unavailable`} description="The current authentication contract does not persist separate invitation, session, or security-policy records. No non-functional controls are shown." />;
  return <PageContainer width="wide"><Header title="Team & Access" subtitle="Business access is enforced server-side by the existing staff role contract." onRefresh={onRefresh} actions={<Button onClick={() => setInvite(true)}>Invite member</Button>} /><Tabs value={tab} tabs={teamTabs.map((value) => ({ value, label: value }))} onChange={setTab} label="Team sections" /><section className="mt-page-section">{content}</section>{invite && <InviteDrawer businessId={business.id} onClose={() => setInvite(false)} onSaved={(member) => { setData((current) => ({ ...current, staff: current.staff.some((item) => item.id === member.id) ? current.staff : [...current.staff, member] })); setInvite(false); }} />}{selected && <MemberDrawer businessId={business.id} member={selected} onClose={() => setSelected(null)} onSaved={(member) => { setData((current) => ({ ...current, staff: current.staff.map((item) => item.id === member.id ? member : item) })); setSelected(member); }} onRemoved={(id) => { setData((current) => ({ ...current, staff: current.staff.filter((item) => item.id !== id) })); setSelected(null); }} />}</PageContainer>;
}

function PermissionMatrix() { const rows = [["Owner", "All business capabilities"], ["Admin", "Administration, payments and team"], ["Manager", "Business and operations access"], ["Kitchen / Cashier", "Assigned workflow access"], ["Viewer", "Read-only assigned access"]]; return <article className="mt-card"><DataTable caption="Server-enforced roles" rows={rows} rowKey={(row) => row[0]} columns={[{ key: "role", header: "Role", cell: (row) => row[0] }, { key: "scope", header: "Server-enforced scope", cell: (row) => row[1] }]} /><p className="mt-type-card-description">Custom roles are not exposed because the current authentication service has no business-scoped custom-role contract.</p></article>; }
function InviteDrawer({ businessId, onClose, onSaved }: { businessId: string; onClose: () => void; onSaved: (member: StaffMember) => void }) { const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [role, setRole] = useState<StaffRole>("viewer"); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const save = async () => { setSaving(true); try { onSaved(await api.inviteStaff(businessId, { email, full_name: name || undefined, role })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not send the invitation."); } finally { setSaving(false); } }; return <DetailsDrawer open onClose={onClose} title="Invite team member" footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button loading={saving} onClick={save} disabled={!email}>Send invite</Button></>}><Stack><Input label="Email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /><Input label="Name" value={name} onChange={(event) => setName(event.target.value)} /><Select label="Role" value={role} onChange={(event) => setRole(event.target.value as StaffRole)}>{["admin", "manager", "kitchen", "cashier", "salon_staff", "kiosk", "viewer"].map((item) => <option value={item} key={item}>{label(item)}</option>)}</Select>{error && <DataState kind="recoverable-error" title="Invitation not sent" description={error} />}</Stack></DetailsDrawer>; }
function MemberDrawer({ businessId, member, onClose, onSaved, onRemoved }: { businessId: string; member: StaffMember; onClose: () => void; onSaved: (member: StaffMember) => void; onRemoved: (id: string) => void }) { const [role, setRole] = useState(member.role); const [saving, setSaving] = useState(false); const save = async () => { setSaving(true); try { onSaved(await api.updateStaff(businessId, member.id, { role })); } finally { setSaving(false); } }; const remove = async () => { if (member.role === "owner" || !window.confirm("Remove this team member?")) return; setSaving(true); try { await api.removeStaff(businessId, member.id); onRemoved(member.id); } finally { setSaving(false); } }; return <DetailsDrawer open onClose={onClose} title={member.full_name || member.email || "Team member"} footer={<><Button variant="secondary" onClick={onClose}>Close</Button><Button loading={saving} onClick={save} disabled={member.role === "owner"}>Save role</Button></>}><Stack><p>{member.email}</p><Select label="Role" value={role} disabled={member.role === "owner"} onChange={(event) => setRole(event.target.value as StaffRole)}>{["admin", "manager", "kitchen", "cashier", "salon_staff", "kiosk", "viewer"].map((item) => <option value={item} key={item}>{label(item)}</option>)}</Select>{member.role === "owner" ? <DataState kind="info" title="Owner protected" description="The current owner cannot be removed or demoted from this screen." /> : <Button variant="danger" loading={saving} onClick={remove}>Remove member</Button>}</Stack></DetailsDrawer>; }

function Payments({ business, data, onRefresh }: AdminProps) { const [tab, setTab] = useState<(typeof paymentTabs)[number]>("Overview"); const [assignments, setAssignments] = useState<Array<Record<string, unknown>>>([]); const [saving, setSaving] = useState(false); useEffect(() => { if (tab === "Location Assignments") void api.paymentLocationAssignments(business.id).then((result) => setAssignments(result.assignments)); }, [business.id, tab]); const assign = async (location: BusinessLocation) => { const provider = data.accounts.find((account) => account.is_enabled && ["active", "connected"].includes(account.connection_status))?.provider; if (!provider) return; setSaving(true); try { await api.savePaymentLocationAssignment(business.id, location.id, { provider, enabled_methods: ["card"], is_override: true }); setAssignments((current) => [...current.filter((item) => item.location_id !== location.id), { location_id: location.id, location_name: location.name, provider, enabled_methods: ["card"], is_override: true }]); } finally { setSaving(false); } }; const content = tab === "Location Assignments" ? <article className="mt-card"><DataTable caption="Payment location assignments" rows={data.locations} rowKey={(location) => location.id} emptyMessage="Create a location before assigning a provider." columns={[{ key: "location", header: "Location", cell: (location) => location.name }, { key: "provider", header: "Provider", cell: (location) => String(assignments.find((item) => item.location_id === location.id)?.provider || "Business default") }, { key: "methods", header: "Methods", cell: (location) => Array.isArray(assignments.find((item) => item.location_id === location.id)?.enabled_methods) ? String((assignments.find((item) => item.location_id === location.id)?.enabled_methods as string[]).join(", ")) : "Business default" }, { key: "action", header: "", cell: (location) => <Button variant="secondary" loading={saving} onClick={() => assign(location)}>Assign connected provider</Button> }]} /></article> : <PaymentsLegacy business={business} data={data} setData={() => undefined} onRefresh={onRefresh} refreshBusiness={async () => null} />; return <PageContainer width="wide"><Header title="Payments" subtitle="Provider setup and location overrides." onRefresh={onRefresh} /><Tabs value={tab} tabs={paymentTabs.map((value) => ({ value, label: value }))} onChange={setTab} label="Payment sections" /><section className="mt-page-section">{content}</section></PageContainer>; }

function Team({ business, data, onRefresh }: AdminProps) { const [tab, setTab] = useState<(typeof teamTabs)[number]>("Members"); const [invitations, setInvitations] = useState<Array<Record<string, unknown>>>([]); const [roles, setRoles] = useState<Array<Record<string, unknown>>>([]); const [policy, setPolicy] = useState<Record<string, unknown> | null>(null); useEffect(() => { if (tab === "Invitations") void api.administrationInvitations(business.id).then((result) => setInvitations(result.invitations)); if (tab === "Roles & Permissions") void api.customRoles(business.id).then((result) => setRoles(result.roles)); if (tab === "Security Policies") void api.securityPolicy(business.id).then(setPolicy); }, [business.id, tab]); const content = tab === "Invitations" ? <InvitationPanel businessId={business.id} invitations={invitations} setInvitations={setInvitations} /> : tab === "Roles & Permissions" ? <CustomRolesPanel businessId={business.id} roles={roles} setRoles={setRoles} /> : tab === "Security Policies" ? <SecurityPanel businessId={business.id} policy={policy} setPolicy={setPolicy} /> : tab === "Sessions" ? <SessionsPanel businessId={business.id} /> : <TeamLegacy business={business} data={data} setData={() => undefined} onRefresh={onRefresh} refreshBusiness={async () => null} />; return <PageContainer width="wide"><Header title="Team & Access" subtitle="Invitations, roles and security policies are scoped to this business." onRefresh={onRefresh} /><Tabs value={tab} tabs={teamTabs.map((value) => ({ value, label: value }))} onChange={setTab} label="Team sections" /><section className="mt-page-section">{content}</section></PageContainer>; }

function InvitationPanel({ businessId, invitations, setInvitations }: { businessId: string; invitations: Array<Record<string, unknown>>; setInvitations: (value: Array<Record<string, unknown>>) => void }) { const [email, setEmail] = useState(""); const create = async () => { const row = await api.createAdministrationInvitation(businessId, { email, role: "viewer", expires_in_days: 7, location_ids: [] }); setInvitations([row, ...invitations]); setEmail(""); }; const update = async (row: Record<string, unknown>, action: "revoke" | "resend") => { if (action === "revoke") { await api.revokeAdministrationInvitation(businessId, String(row.id)); setInvitations(invitations.map((item) => item.id === row.id ? { ...item, status: "revoked" } : item)); } else { const next = await api.resendAdministrationInvitation(businessId, String(row.id)); setInvitations(invitations.map((item) => item.id === row.id ? { ...item, ...next } : item)); } }; return <article className="mt-card"><Stack><Input label="Invite by email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} /><Button disabled={!email} onClick={create}>Create invitation</Button><DataTable caption="Invitations" rows={invitations} rowKey={(row) => String(row.id)} emptyMessage="No invitations." columns={[{ key: "email", header: "Email", cell: (row) => String(row.email) }, { key: "role", header: "Role", cell: (row) => label(String(row.role)) }, { key: "status", header: "Status", cell: (row) => String(row.status || "pending") }, { key: "expires", header: "Expires", cell: (row) => date(String(row.expires_at)) }, { key: "actions", header: "", cell: (row) => <Stack><Button variant="secondary" onClick={() => void update(row, "resend")} disabled={row.status === "accepted"}>Resend</Button><Button variant="secondary" onClick={() => void update(row, "revoke")} disabled={row.status !== "pending"}>Revoke</Button></Stack> }]} /></Stack></article>; }

function SessionsPanel({ businessId }: { businessId: string }) { const [rows, setRows] = useState<Array<Record<string, unknown>>>([]); useEffect(() => { void api.administrationSessions(businessId).then((result) => setRows(result.sessions)); }, [businessId]); const revoke = async (id: string) => { await api.revokeAdministrationSession(businessId, id); setRows(rows.map((row) => row.id === id ? { ...row, revoked_at: new Date().toISOString() } : row)); }; return <article className="mt-card"><Stack><Button variant="secondary" onClick={() => void api.revokeOtherAdministrationSessions(businessId)}>Revoke other sessions</Button><DataTable caption="Sessions" rows={rows} rowKey={(row) => String(row.id)} emptyMessage="No active sessions." columns={[{ key: "email", header: "Account", cell: (row) => String(row.email) }, { key: "active", header: "Last active", cell: (row) => date(String(row.last_active_at)) }, { key: "state", header: "State", cell: (row) => row.revoked_at ? "Revoked" : row.is_current ? "Current" : "Active" }, { key: "action", header: "", cell: (row) => <Button variant="secondary" disabled={Boolean(row.revoked_at)} onClick={() => void revoke(String(row.id))}>Revoke</Button> }]} /></Stack></article>; }
function CustomRolesPanel({ businessId, roles, setRoles }: { businessId: string; roles: Array<Record<string, unknown>>; setRoles: (value: Array<Record<string, unknown>>) => void }) { const [name, setName] = useState(""); const create = async () => { const row = await api.createCustomRole(businessId, { name, permissions: ["insights.read"] }); setRoles([...roles, row]); setName(""); }; return <article className="mt-card"><Stack><Input label="Custom role name" value={name} onChange={(event) => setName(event.target.value)} /><Button disabled={!name} onClick={create}>Create read-only role</Button><DataTable caption="Custom roles" rows={roles} rowKey={(row) => String(row.id)} emptyMessage="No custom roles." columns={[{ key: "name", header: "Role", cell: (row) => String(row.name) }, { key: "permissions", header: "Permissions", cell: (row) => Array.isArray(row.permissions) ? String((row.permissions as string[]).join(", ")) : "" }]} /></Stack></article>; }
function SecurityPanel({ businessId, policy, setPolicy }: { businessId: string; policy: Record<string, unknown> | null; setPolicy: (value: Record<string, unknown>) => void }) { const save = async () => { const next = await api.updateSecurityPolicy(businessId, { ...(policy || {}), session_duration_minutes: 480, reauthentication_minutes: 15, invitation_expiry_days: 7, two_factor_required: false, inactive_account_days: 90 }); setPolicy(next); }; return <article className="mt-card"><Stack><p>Session duration: {String(policy?.session_duration_minutes || 480)} minutes</p><p>Invitation expiry: {String(policy?.invitation_expiry_days || 7)} days</p><Button onClick={save}>Save policy defaults</Button><DataState kind="stale" title="2FA preference only" description="The preference is stored, but 2FA is not claimed as enforced until the authentication flow supports it." /></Stack></article>; }

function BusinessSettings({ business, onRefresh, refreshBusiness }: AdminProps) { const [form, setForm] = useState({ name: business.name || "", contact_phone: business.contact_phone || "", timezone: business.timezone || "", currency_code: business.currency_code || "", address_line1: business.address_line1 || "", city: business.city || "", country: business.country || "" }); const [saved, setSaved] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const change = (key: keyof typeof form, value: string) => { setForm((current) => ({ ...current, [key]: value })); setSaved(false); }; const save = async () => { setSaving(true); setError(""); try { await api.updateBusiness(business.id, form); await refreshBusiness(); setSaved(true); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save business settings."); } finally { setSaving(false); } }; return <PageContainer width="standard"><Header title="Business Settings" subtitle="Business-wide defaults only. Kiosk branding remains in Kiosk Experience." onRefresh={onRefresh} /><ResponsiveGrid columns={2}><article className="mt-card"><SectionHeader title="Business Profile" /><Stack><Input label="Display name" value={form.name} onChange={(event) => change("name", event.target.value)} /><Input label="Contact phone" value={form.contact_phone} onChange={(event) => change("contact_phone", event.target.value)} /><Input label="Address" value={form.address_line1} onChange={(event) => change("address_line1", event.target.value)} /><Input label="City" value={form.city} onChange={(event) => change("city", event.target.value)} /><Input label="Country" value={form.country} onChange={(event) => change("country", event.target.value)} /></Stack></article><article className="mt-card"><SectionHeader title="Regional Settings" /><Stack><Input label="Default timezone" value={form.timezone} onChange={(event) => change("timezone", event.target.value)} /><Input label="Default currency" value={form.currency_code} maxLength={3} onChange={(event) => change("currency_code", event.target.value.toUpperCase())} /><DataState kind="info" title="Other settings are contract-led" description="Taxes, receipts, notifications, ownership transfer, retention and destructive business actions do not receive non-persistent controls." /></Stack></article></ResponsiveGrid>{error && <section className="mt-page-section"><DataState kind="recoverable-error" title="Settings not saved" description={error} /></section>}{!saved && <UnsavedChangesBar message="You have unsaved business settings." actions={<><Button variant="secondary" onClick={() => { setSaved(true); onRefresh(); }}>Discard</Button><Button loading={saving} onClick={save}>Save changes</Button></>} />}</PageContainer>; }

function ActivityLog({ business, data, setData, onRefresh }: AdminProps) { const [search, setSearch] = useState(""); const [selected, setSelected] = useState<AdministrationActivity | null>(null); const [loading, setLoading] = useState(false); const searchEvents = async () => { setLoading(true); try { const result = await api.administrationActivity(business.id, search); setData((current) => ({ ...current, activity: result.events })); } finally { setLoading(false); } }; return <PageContainer width="wide"><Header title="Activity Log" subtitle="Immutable administrative history. Sensitive values are masked." onRefresh={onRefresh} /><FilterBar actions={<Button variant="secondary" loading={loading} onClick={searchEvents}>Apply filters</Button>}><SearchInput label="Search activity" placeholder="Search action, record or actor" value={search} onChange={(event) => setSearch(event.target.value)} /><Select label="Section" defaultValue="all"><option value="all">All sections</option><option value="payments">Payments</option><option value="locations">Locations</option><option value="team">Team</option></Select></FilterBar><article className="mt-card"><ActivityTable rows={data.activity} onSelect={setSelected} /></article>{selected && <DetailsDrawer open onClose={() => setSelected(null)} title={label(selected.action)} footer={<Button variant="secondary" onClick={() => setSelected(null)}>Close</Button>}><Stack><p>Time: {date(selected.created_at)}</p><p>Actor: {selected.actor_name || selected.actor_email || "System"}</p><p>Role: {selected.actor_role ? label(selected.actor_role) : "System"}</p><p>Record: {selected.entity || "Not recorded"}</p><pre className="mt-admin-metadata">{JSON.stringify(selected.metadata || {}, null, 2)}</pre></Stack></DetailsDrawer>}</PageContainer>; }

function ActivityTable({ rows, onSelect }: { rows: AdministrationActivity[]; onSelect?: (event: AdministrationActivity) => void }) { return <DataTable caption="Administrative activity" rows={rows} rowKey={(row) => row.id} emptyMessage="No administrative activity matches the current filters." columns={[{ key: "time", header: "Time", cell: (row) => date(row.created_at) }, { key: "actor", header: "Actor", cell: (row) => row.actor_name || row.actor_email || "System" }, { key: "action", header: "Action", cell: (row) => onSelect ? <button className="mt-table-link" onClick={() => onSelect(row)}>{label(row.action)}</button> : label(row.action) }, { key: "record", header: "Record", cell: (row) => row.entity || "—" }, { key: "role", header: "Role", cell: (row) => row.actor_role ? label(row.actor_role) : "System" }]} />; }
function mask(value: string) { return value.length <= 4 ? "••••" : `••••${value.slice(-4)}`; }
function IntegrationsSafe({ business, onRefresh }: AdminProps) {
  const [tab, setTab] = useState("Connected");
  const [rows, setRows] = useState<Array<Record<string, unknown>>>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const result = tab === "Developer Tools" ? await api.integrationApiKeys(business.id) : tab === "Webhooks" ? await api.integrationWebhooks(business.id) : tab === "Activity" ? await api.integrationActivity(business.id) : await api.integrations(business.id);
      const payload = result as { integrations?: Array<Record<string, unknown>>; api_keys?: Array<Record<string, unknown>>; webhooks?: Array<Record<string, unknown>>; events?: Array<Record<string, unknown>> };
      setRows(payload.integrations || payload.api_keys || payload.webhooks || payload.events || []);
    } catch (cause) { setRows([]); setError(cause instanceof Error ? cause.message : "This section is temporarily unavailable."); }
    finally { setLoading(false); }
  }, [business.id, tab]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  return <PageContainer width="wide"><Header title="Integrations" subtitle="External connectors and hardware mappings; physical Menu Tap devices remain in Operations." onRefresh={onRefresh} /><Tabs value={tab} tabs={["Connected", "All Integrations", "Devices & Hardware", "Developer Tools", "Webhooks", "Activity"].map((value) => ({ value, label: value }))} onChange={setTab} label="Integration sections" /><section className="mt-page-section"><article className="mt-card"><div className="mt-card-header"><h2>{tab}</h2><Button variant="secondary" loading={loading} onClick={() => void load()}>Refresh section</Button></div>{error ? <DataState kind="recoverable-error" title="Section unavailable" description={error} action={<Button variant="secondary" onClick={() => void load()}>Try again</Button>} /> : <DataTable caption={`${tab} records`} rows={rows} rowKey={(row) => String(row.id || row.key_prefix || row.endpoint_url || row.action)} emptyMessage={`No ${tab.toLowerCase()} records.`} columns={[{ key: "name", header: "Name", cell: (row) => String(row.name || row.key_prefix || row.endpoint_url || row.action || "Record") }, { key: "type", header: "Type", cell: (row) => String(row.integration_type || (row.events ? "Webhook" : "Integration")) }, { key: "status", header: "Status", cell: (row) => String(row.status || (row.is_active === false ? "Disabled" : row.revoked_at ? "Revoked" : "Active")) }]} />}</article>{tab === "Devices & Hardware" && <DataState kind="stale" title="Hardware mappings are created with integration accounts" description="Physical Menu Tap device actions remain in Operations." />}</section></PageContainer>;
}
