"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Image from "next/image";
import { AlertTriangle, Check, ChevronRight, Lock, Minus, Pause, Plus, RefreshCw, Search, Trash2, UtensilsCrossed, Wifi, WifiOff } from "lucide-react";
import { api } from "@/lib/api";
import { formatCurrency } from "@/lib/formatters";
import type { Category, KioskMenu, LiveDeviceContext, ModifierOption, Order, Product } from "@/lib/types";
import { connectionLabel, elapsedLabel, kitchenLabel, kitchenStage } from "@/features/staff/status";
import { listQueuedCounterOrders, queueCounterOrder, removeQueuedCounterOrder, updateQueuedCounterOrder } from "./offline-store";
import { testDeviceContext, testOrder, testSessionStateMessage } from "@/features/test-runtime";
import { AutoRecoveringState } from "@/components/ui/AutoRecoveringState";
import { CounterPosSkeleton } from "@/components/ui/Skeletons";

type Tab = "ordering" | "kitchen" | "handover";
type Source = "counter" | "kiosk";
type CartLine = { product: Product; quantity: number; customizations: Array<{ option_id: string; name: string; price_delta: number }> };
type PendingPaymentRow = { id: string; business_id?: string; amount?: number; status: string; item_count?: number; claim?: { device_id: string }; order?: { order_number?: string | number | null; public_token?: string | null; order_type?: string; table_label?: string | null; total_amount?: number; notes?: string | null; items?: Array<{ product_id: string; quantity: number; name?: string; product_name?: string }> } };
const makeId = () => crypto.randomUUID();

export function CounterApp({ runtimeMode = "live" }: { runtimeMode?: "live" | "test" }) {
  const isTest = runtimeMode === "test";
  const router = useRouter();
  const params = useSearchParams();
  const [tab, setTab] = useState<Tab>((params.get("tab") as Tab) || "ordering");
  const [context, setContext] = useState<LiveDeviceContext | null>(null);
  const [menu, setMenu] = useState<KioskMenu | null>(null);
  const [orders, setOrders] = useState<Order[]>([]);
  const [history, setHistory] = useState<Order[]>([]);
  const [pending, setPending] = useState<PendingPaymentRow[]>([]);
  const [held, setHeld] = useState<Array<Record<string, unknown>>>([]);
  const [cart, setCart] = useState<CartLine[]>([]);
  const [source, setSource] = useState<Source>("counter");
  const [orderType, setOrderType] = useState<"dine_in" | "takeaway">("takeaway");
  const [table, setTable] = useState("");
  const [notes, setNotes] = useState("");
  const [paymentMethod, setPaymentMethod] = useState("cash");
  const [category, setCategory] = useState("all");
  const [search, setSearch] = useState("");
  const [selectedOrder, setSelectedOrder] = useState<Order | null>(null);
  const [selectedPayment, setSelectedPayment] = useState<PendingPaymentRow | null>(null);
  const [modifierProduct, setModifierProduct] = useState<Product | null>(null);
  const [modifierSelection, setModifierSelection] = useState<ModifierOption[]>([]);
  const [queued, setQueued] = useState(0);
  const [online, setOnline] = useState(() => typeof navigator === "undefined" || navigator.onLine);
  const [loading, setLoading] = useState(true);
  const [shellError, setShellError] = useState("");
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState("");
  const [now, setNow] = useState(0);

  const setAreaError = (area: string, value = "") => setErrors((current) => ({ ...current, [area]: value }));
  const syncLocal = useCallback(async () => {
    if (isTest) { setQueued(0); return; }
    const local = await listQueuedCounterOrders();
    if (!online) { setQueued(local.length); return; }
    for (const item of local) {
      try { await api.liveCounterSessionCreateOrder(item.payload, item.idempotencyKey); await removeQueuedCounterOrder(item.localId); }
      catch (error) { await updateQueuedCounterOrder({ ...item, status: "failed", retryCount: item.retryCount + 1, lastError: error instanceof Error ? error.message : "Synchronization failed" }); }
    }
    setQueued((await listQueuedCounterOrders()).length);
  }, [isTest, online]);
  const refreshOperational = useCallback(async () => {
    const businessId = menu?.business.id || context?.business.id || "test";
    if (isTest) {
      const [nextOrders, nextHistory, nextPending] = await Promise.allSettled([api.testCounterKitchenOrders(), api.testCounterHandoverHistory(), api.testCounterPendingPayments()]);
      if (nextOrders.status === "fulfilled") { setOrders(nextOrders.value.orders.map((order) => testOrder(order, businessId))); setAreaError("queue"); } else setAreaError("queue", "Couldn't load Kitchen Queue.");
      if (nextHistory.status === "fulfilled") { setHistory(nextHistory.value.orders.map((order) => testOrder(order, businessId))); setAreaError("history"); } else setAreaError("history", "Couldn't load Handover History.");
      setHeld([]); setAreaError("held");
      if (nextPending.status === "fulfilled") { setPending(nextPending.value.orders.map((raw) => { const order = testOrder(raw, businessId); return { id: order.id, business_id: order.business_id, amount: order.total_amount, status: order.payment_status, item_count: order.order_items?.reduce((count, item) => count + item.quantity, 0), order: { ...order, items: order.order_items?.map((item) => ({ product_id: item.product_id || "", quantity: item.quantity, product_name: item.product_name })) } }; })); setAreaError("payments"); } else setAreaError("payments", "Payment status unavailable.");
      return;
    }
    const [nextOrders, nextHistory, nextHeld, nextPending] = await Promise.allSettled([api.liveCounterKitchenOrders(), api.liveCounterHandoverHistory(), api.liveCounterHeldOrders(), api.liveCounterPendingPayments()]);
    if (nextOrders.status === "fulfilled") { setOrders(nextOrders.value.orders); setAreaError("queue"); } else setAreaError("queue", "Couldn't load Kitchen Queue.");
    if (nextHistory.status === "fulfilled") { setHistory(nextHistory.value.orders); setAreaError("history"); } else setAreaError("history", "Couldn't load Handover History.");
    if (nextHeld.status === "fulfilled") { setHeld(nextHeld.value.held_orders); setAreaError("held"); } else setAreaError("held", "Couldn't load held orders.");
    if (nextPending.status === "fulfilled") { setPending(nextPending.value.payments as PendingPaymentRow[]); setAreaError("payments"); } else setAreaError("payments", "Payment status unavailable.");
  }, [context?.business.id, isTest, menu?.business.id]);
  const load = useCallback(async () => {
    setLoading(true);
    try {
      const nextMenu = isTest ? await api.testKioskSessionMenu() : await api.liveCounterSessionMenu();
      const session = isTest ? await api.testRuntimeContext("counter") : await api.liveDeviceSessionContext("counter");
      setContext(isTest ? testDeviceContext(nextMenu, "counter") : (session as LiveDeviceContext));
      setMenu(nextMenu); setShellError(""); setAreaError("menu");
      await Promise.all([syncLocal(), refreshOperational()]);
    } catch (error) {
      setShellError(error instanceof Error ? error.message : isTest ? "Test session unavailable or expired." : "Counter session unavailable. Pair or reactivate this device.");
    } finally { setLoading(false); }
  }, [isTest, refreshOperational, syncLocal]);
  useEffect(() => { const initial = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(initial); }, [load]);
  useEffect(() => { const onlineHandler = () => { setOnline(true); void load(); }; const offlineHandler = () => setOnline(false); const timer = window.setInterval(() => setNow(Date.now()), 1000); const refreshTimer = window.setInterval(() => { if (navigator.onLine && document.visibilityState === "visible") void refreshOperational(); }, 15000); addEventListener("online", onlineHandler); addEventListener("offline", offlineHandler); return () => { removeEventListener("online", onlineHandler); removeEventListener("offline", offlineHandler); clearInterval(timer); clearInterval(refreshTimer); }; }, [load, refreshOperational]);
  const switchTab = (next: Tab) => { setTab(next); router.replace(isTest ? `/test/counter?tab=${next}` : `/device?tab=${next}`); };
  const currency = menu?.business.currency_symbol || "";
  const products = useMemo(() => (menu?.products || []).filter((product) => (category === "all" || product.category_id === category) && product.name.toLowerCase().includes(search.toLowerCase())), [category, menu?.products, search]);
  const subtotal = cart.reduce((sum, line) => sum + (line.product.price + line.customizations.reduce((total, item) => total + item.price_delta, 0)) * line.quantity, 0);
  const tax = subtotal * Number(menu?.business.tax_percent || 0) / 100;
  const total = subtotal + tax;
  const itemCount = cart.reduce((count, line) => count + line.quantity, 0);
  const productQuantities = useMemo(() => cart.reduce((quantities, line) => quantities.set(line.product.id, (quantities.get(line.product.id) || 0) + line.quantity), new Map<string, number>()), [cart]);
  const readyOrders = orders.filter((order) => order.status === "ready");
  const queueOrders = orders.filter((order) => order.status !== "ready" && order.status !== "completed").slice(0, 4);
  const addProduct = (product: Product) => { if (!product.is_available) return; if (product.modifier_groups?.length) { setModifierProduct(product); setModifierSelection(product.modifier_groups.flatMap((group) => group.options.filter((option) => option.is_default))); return; } setCart((current) => { const index = current.findIndex((line) => line.product.id === product.id && !line.customizations.length); return index < 0 ? [...current, { product, quantity: 1, customizations: [] }] : current.map((line, lineIndex) => lineIndex === index ? { ...line, quantity: line.quantity + 1 } : line); }); };
  const decreaseProduct = (product: Product) => setCart((current) => { const index = current.map((line) => line.product.id).lastIndexOf(product.id); return index < 0 ? current : current.map((line, lineIndex) => lineIndex === index ? { ...line, quantity: line.quantity - 1 } : line).filter((line) => line.quantity > 0); });
  const confirmModifiers = () => { if (!modifierProduct) return; for (const group of modifierProduct.modifier_groups || []) { const count = modifierSelection.filter((option) => option.group_id === group.id).length; if (group.is_required && count < group.min_select) { setNotice(`Select ${group.name} before adding ${modifierProduct.name}.`); return; } if (group.max_select && count > group.max_select) { setNotice(`Select no more than ${group.max_select} ${group.name} options.`); return; } } setCart((current) => [...current, { product: modifierProduct, quantity: 1, customizations: modifierSelection.map((option) => ({ option_id: option.id, name: option.name, price_delta: option.price_delta })) }]); setModifierProduct(null); setModifierSelection([]); };
  const orderPayload = () => isTest
    ? { source: "counter", order_type: orderType, table_label: orderType === "dine_in" ? table || null : null, notes: notes || null, idempotency_key: `counter-${makeId()}`, items: cart.map((line) => ({ product_id: line.product.id, quantity: line.quantity, modifiers: line.customizations })) }
    : { order_type: orderType, table_label: orderType === "dine_in" ? table || null : null, notes: notes || null, payment_method: paymentMethod, items: cart.map((line) => ({ product_id: line.product.id, quantity: line.quantity, customizations: line.customizations })) };
  const newOrder = () => { if (!cart.length || window.confirm("Discard the current order? Choose Cancel to keep it, or OK to discard it.")) { setCart([]); setTable(""); setNotes(""); setNotice(""); } };
  const holdOrder = async () => { if (!cart.length) return; if (isTest) { setNotice("Test Counter does not persist unfinished drafts."); return; } setBusy("hold"); try { await api.liveCounterHoldOrder(orderPayload()); setCart([]); setTable(""); setNotes(""); setNotice("Order held. It has not been sent to Kitchen."); await refreshOperational(); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not hold this order."); } finally { setBusy(""); } };
  const placeOrder = async () => { if (!cart.length || (orderType === "dine_in" && !table.trim())) { setNotice(orderType === "dine_in" ? "Add a table number before payment." : "Add an item before payment."); return; } const payload = orderPayload(); const idempotencyKey = `counter-${makeId()}`; setBusy("payment"); try { if (isTest) { const created = await api.testRuntimeCreateOrder(payload); await api.testRuntimeMarkPaid(String(created.id)); } else { const order = await api.liveCounterSessionCreateOrder(payload, idempotencyKey); const payment = order.payment?.payment; if (payment?.id && ["cash", "pay_at_counter"].includes(paymentMethod)) await api.liveCounterSessionMarkPaid(payment.id, { business_id: order.business_id, amount: order.total_amount, method: paymentMethod }); } setCart([]); setTable(""); setNotes(""); setNotice("Payment confirmed and order sent to Kitchen."); await refreshOperational(); } catch (error) { const message = error instanceof Error ? error.message : "Payment could not be confirmed."; if (!isTest && (!online || /network|offline|fetch/i.test(message))) { await queueCounterOrder({ localId: makeId(), idempotencyKey, payload: payload as Record<string, unknown>, createdAt: new Date().toISOString(), status: "pending", retryCount: 0 }); setQueued((count) => count + 1); setNotice("Saved locally. Payment and Kitchen dispatch will wait for a safe retry."); } else setNotice(message); } finally { setBusy(""); } };
  const handover = async (order: Order) => { setBusy(order.id); try { if (isTest) await api.testCounterHandover(order.id); else await api.liveCounterSessionCompleteOrder(order.id, { business_id: order.business_id }); setNotice(`Order #${order.order_number || order.public_token} handed over.`); await refreshOperational(); } catch (error) { setNotice(error instanceof Error ? error.message : "Handover could not be completed."); } finally { setBusy(""); } };
  const resumeHeld = async (item: Record<string, unknown>) => { setBusy(String(item.id)); try { const resumed = await api.liveCounterResumeHeldOrder(String(item.id)); const payload = resumed.payload as { items?: Array<{ product_id: string; quantity: number; customizations?: Array<{ option_id: string; name: string; price_delta: number }> }>; order_type?: "dine_in" | "takeaway"; table_label?: string; notes?: string }; const lines = (payload.items || []).flatMap((entry) => { const product = menu?.products.find((candidate) => candidate.id === entry.product_id); return product ? [{ product, quantity: entry.quantity, customizations: entry.customizations || [] }] : []; }); setCart(lines); setOrderType(payload.order_type || "takeaway"); setTable(payload.table_label || ""); setNotes(payload.notes || ""); setSource("counter"); switchTab("ordering"); await refreshOperational(); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not resume held order."); } finally { setBusy(""); } };
  if (shellError && !context) {
    return (
      <main className="staff-recovery">
        <section style={{ maxWidth: "500px", width: "100%", padding: "12px" }}>
          <AutoRecoveringState
            title="MenuTap Counter"
            description={isTest ? testSessionStateMessage(new Error(shellError)) : shellError}
            onRetry={load}
            action={
              <button
                type="button"
                className="mt-button mt-button--secondary"
                onClick={() => router.push(isTest ? "/dashboard/test" : "/device/start")}
              >
                {isTest ? "Return to Test Hub" : "Pair or recover device"}
              </button>
            }
          />
        </section>
      </main>
    );
  }
  if (loading && !context) return <CounterPosSkeleton />;
  return <main className="staff-app counter-app-v2">
    <CounterHeader context={context} online={online} queued={queued} testMode={isTest} onLock={() => isTest ? router.push("/dashboard/test") : void api.clearLiveDeviceSession().then(() => router.push("/device/start"))} />
    <nav className="staff-primary-nav counter-primary-nav" aria-label="Counter application" role="tablist">{([ ["ordering", "Counter Ordering"], ["kitchen", "Kitchen Orders"], ["handover", "Handover History"] ] as const).map(([key, label]) => <button key={key} role="tab" aria-selected={tab === key} className={tab === key ? "active" : ""} onClick={() => switchTab(key)}>{label}{key === "kitchen" && pending.length > 0 ? <b>{pending.length}</b> : null}</button>)}</nav>
    <CounterStatusStrip online={online} queued={queued} orders={orders} pending={pending.length} deviceStatus={context?.device.status} paymentUnavailable={!!errors.payments} />
    {notice && <p className="staff-notice" role="status">{notice}</p>}
    {tab === "ordering" && <section className="counter-main-grid">
      <section className="counter-order-workspace"><div className="counter-order-toolbar"><div className="segmented"><button className={orderType === "takeaway" ? "selected" : ""} onClick={() => setOrderType("takeaway")}>Takeaway</button><button className={orderType === "dine_in" ? "selected" : ""} onClick={() => setOrderType("dine_in")}>Dine In</button></div><label className="staff-search"><Search size={17}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search menu items…" aria-label="Search menu items" /></label><button className="staff-button" disabled={!cart.length || !!busy} onClick={() => void holdOrder()}><Pause size={16}/> Hold Order</button><button className="staff-button primary" onClick={newOrder}><Plus size={17}/> New Order</button></div>
        <div className="counter-source-row"><strong>Order Source:</strong><button className={source === "counter" ? "selected" : ""} onClick={() => setSource("counter")}>Counter Entry</button><button className={source === "kiosk" ? "selected" : ""} onClick={() => setSource("kiosk")}>Kiosk Pay at Counter {pending.length > 0 ? <b>{pending.length}</b> : null}</button>{orderType === "dine_in" && <input value={table} onChange={(event) => setTable(event.target.value)} placeholder="Table number" aria-label="Table number" />}</div>
        <div className="counter-product-cart"><section className="counter-menu-pane"><div className="counter-categories"><button className={category === "all" ? "selected" : ""} onClick={() => setCategory("all")}>All items</button>{menu?.categories.filter((item) => item.is_active).map((item: Category) => <button className={category === item.id ? "selected" : ""} key={item.id} onClick={() => setCategory(item.id)}>{item.name}</button>)}</div>{errors.menu ? <AreaError text={errors.menu} retry={load} /> : <div className="counter-product-grid">{products.map((product) => <ProductCard key={product.id} product={product} currency={currency} quantity={productQuantities.get(product.id) || 0} onAdd={() => addProduct(product)} onDecrease={() => decreaseProduct(product)} />)}{!products.length && <Empty text="No menu items match this search." />}</div>}</section>
          {source === "counter" ? <CurrentOrder cart={cart} itemCount={itemCount} currency={currency} subtotal={subtotal} tax={tax} total={total} notes={notes} paymentMethod={paymentMethod} busy={busy} queued={queued} onNotes={setNotes} onPaymentMethod={setPaymentMethod} onQuantity={(index, delta) => setCart((current) => current.map((line, currentIndex) => currentIndex === index ? { ...line, quantity: Math.max(0, line.quantity + delta) } : line).filter((line) => line.quantity > 0))} onRemove={(index) => setCart((current) => current.filter((_, currentIndex) => currentIndex !== index))} onPay={() => void placeOrder()} /> : <PendingPayments rows={pending} currency={currency} error={errors.payments} onSelect={setSelectedPayment} />}</div>
      </section><aside className="counter-right-rail"><QueuePanel orders={queueOrders} error={errors.queue} now={now} onOpen={(order) => { setSelectedOrder(order); switchTab("kitchen"); }} onView={() => switchTab("kitchen")} /><ReadyPanel orders={readyOrders} busy={busy} currency={currency} onHandover={handover} /><DeviceAlert status={context?.device.status} /></aside>
    </section>}
    {tab === "kitchen" && <CounterOrdersPage orders={orders} pending={pending} error={errors.queue} currency={currency} busy={busy} now={now} onRefresh={refreshOperational} onHandover={handover} selected={selectedOrder} onSelect={setSelectedOrder} onPayment={setSelectedPayment} />}
    {tab === "handover" && <HistoryPage orders={history} error={errors.history} currency={currency} now={now} onRefresh={refreshOperational} />}
    {held.length > 0 && tab === "ordering" && <section className="counter-held-panel"><div><h2>Held Counter Orders</h2><span>Incomplete orders only — not sent to Kitchen</span></div>{held.map((item) => <article key={String(item.id)}><span><b>{String(item.order_reference || "Held order")}</b><small>{item.created_at ? new Date(String(item.created_at)).toLocaleTimeString() : "Saved"}</small></span><button className="staff-button" disabled={!!busy} onClick={() => void resumeHeld(item)}>Resume</button></article>)}</section>}
    {modifierProduct && <ModifierDialog product={modifierProduct} selected={modifierSelection} currency={currency} onToggle={(option) => setModifierSelection((current) => current.some((item) => item.id === option.id) ? current.filter((item) => item.id !== option.id) : [...current, option])} onClose={() => setModifierProduct(null)} onConfirm={confirmModifiers} />}
    {selectedPayment && <PaymentDialog row={selectedPayment} currency={currency} testMode={isTest} onClose={() => setSelectedPayment(null)} onRefresh={refreshOperational} />}
  </main>;
}

function CounterHeader({ context, online, queued, testMode, onLock }: { context: LiveDeviceContext | null; online: boolean; queued: number; testMode: boolean; onLock: () => void }) { return <header className="staff-header counter-header"><div className="staff-brand"><strong>MenuTap</strong><span>COUNTER</span>{testMode && <em>TEST MODE</em>}</div><div className="staff-location"><b>{context?.device.location_label || "Assigned location"}</b><small>{context?.business.name || "Counter session"}</small></div><div className="staff-header-actions"><span className={`staff-connection ${online ? "healthy" : "warning"}`}>{online ? <Wifi size={16}/> : <WifiOff size={16}/>}{testMode ? "Test Session · Current" : connectionLabel(online, queued)}</span><button className="icon-button" aria-label="Lock device" onClick={onLock}><Lock size={18}/></button></div></header>; }
function CounterStatusStrip({ online, queued, orders, pending, deviceStatus, paymentUnavailable }: { online: boolean; queued: number; orders: Order[]; pending: number; deviceStatus?: string; paymentUnavailable: boolean }) { const active = orders.filter((order) => order.status !== "ready" && order.status !== "completed").length; return <section className="counter-status-strip" aria-label="Operational status"><StatusCell label="Payment Terminal" value={paymentUnavailable ? "Status unavailable" : "Not reported"} tone={paymentUnavailable ? "warning" : "neutral"}/><StatusCell label="Kitchen" value={online ? `${active} active orders` : "Offline"} tone={online ? "success" : "warning"}/><StatusCell label="Kiosk" value="Not reported" tone="neutral"/><StatusCell label="Device Alert" value={deviceStatus === "warning" || deviceStatus === "issue" ? "Investigate" : "No device alerts"} tone={deviceStatus === "warning" || deviceStatus === "issue" ? "error" : "success"}/><StatusCell label="Offline Sync" value={online ? (queued ? `${queued} pending sync` : "Clear") : "Offline"} tone={online && !queued ? "success" : "warning"}/><StatusCell label="Kiosk Orders" value={pending ? `${pending} awaiting payment` : "Clear"} tone={pending ? "warning" : "success"}/></section>; }
function StatusCell({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className={`status-cell ${tone}`}><small>{label}</small><b>{value}</b></div>; }
function ProductCard({ product, currency, quantity, onAdd, onDecrease }: { product: Product; currency: string; quantity: number; onAdd: () => void; onDecrease: () => void }) { return <article className={`counter-product-card ${product.is_available ? "" : "unavailable"}`}><div className="product-image">{product.primary_image_path ? <Image src={product.primary_image_path} alt="" fill sizes="(max-width: 767px) 45vw, 145px" unoptimized /> : <UtensilsCrossed size={28}/>}</div><div><b>{product.name}</b><small>{formatCurrency(product.price, currency)}</small></div>{!product.is_available ? <span className="status-badge">Unavailable</span> : quantity ? <div className="quantity product-quantity"><button aria-label={`Decrease ${product.name} quantity`} onClick={onDecrease}><Minus size={15}/></button><b>{quantity}</b><button aria-label={`Increase ${product.name} quantity`} onClick={onAdd}><Plus size={15}/></button></div> : <button className="staff-button" onClick={onAdd}><Plus size={15}/> Add</button>}</article>; }
function CurrentOrder({ cart, itemCount, currency, subtotal, tax, total, notes, paymentMethod, busy, queued, onNotes, onPaymentMethod, onQuantity, onRemove, onPay }: { cart: CartLine[]; itemCount: number; currency: string; subtotal: number; tax: number; total: number; notes: string; paymentMethod: string; busy: string; queued: number; onNotes: (value: string) => void; onPaymentMethod: (value: string) => void; onQuantity: (index: number, delta: number) => void; onRemove: (index: number) => void; onPay: () => void }) { return <aside className="current-order"><header><div><h2>Current Order</h2><small>Counter Entry · Draft</small></div><span>{itemCount} {itemCount === 1 ? "item" : "items"}</span></header><div className="cart-lines">{cart.map((line, index) => <article key={`${line.product.id}-${index}`}><div className="quantity"><button aria-label={`Decrease ${line.product.name} quantity`} onClick={() => onQuantity(index, -1)}><Minus size={14}/></button><b>{line.quantity}</b><button aria-label={`Increase ${line.product.name} quantity`} onClick={() => onQuantity(index, 1)}><Plus size={14}/></button></div><div><b>{line.product.name}</b><small>{line.customizations.map((item) => item.name).join(", ") || "No modifiers"}</small></div><span>{formatCurrency((line.product.price + line.customizations.reduce((sum, item) => sum + item.price_delta, 0)) * line.quantity, currency)}<button aria-label={`Remove ${line.product.name}`} onClick={() => onRemove(index)}><Trash2 size={15}/></button></span></article>)}{!cart.length && <Empty text="No items added yet. Choose an item from the menu to start this order." />}</div><details className="item-note"><summary>+ Add Item Note</summary><textarea value={notes} onChange={(event) => onNotes(event.target.value)} placeholder="Order note" /></details><div className="totals"><span>Subtotal <b>{formatCurrency(subtotal, currency)}</b></span><span>Tax <b>{formatCurrency(tax, currency)}</b></span><strong>Total <b>{formatCurrency(total, currency)}</b></strong></div><label className="payment-select">Payment method<select value={paymentMethod} onChange={(event) => onPaymentMethod(event.target.value)}><option value="cash">Cash</option><option value="pay_at_counter">Pay at Counter</option></select></label><button className="staff-button primary pay-button" disabled={!cart.length || !!busy} onClick={onPay}>{busy === "payment" ? "Confirming payment…" : "Pay & Send to Kitchen"}</button>{queued ? <small className="offline-copy">{queued} order{queued > 1 ? "s" : ""} awaiting safe sync.</small> : null}</aside>; }
function PendingPayments({ rows, currency, error, onSelect }: { rows: PendingPaymentRow[]; currency: string; error?: string; onSelect: (row: PendingPaymentRow) => void }) { return <aside className="current-order pending-order"><header><div><h2>Kiosk Pay at Counter</h2><small>Kitchen receives these only after payment confirmation.</small></div><span>{rows.length}</span></header>{error ? <AreaError text={error} /> : rows.map((row) => <button className="pending-payment" key={row.id} onClick={() => onSelect(row)}><b>#{row.order?.order_number || row.order?.public_token || row.id.slice(0, 8)}</b><small>{row.item_count || 0} items · {row.order?.order_type || "Takeaway"}</small><span>{currency}{Number(row.amount || row.order?.total_amount || 0).toFixed(2)}<ChevronRight size={16}/></span></button>)}{!rows.length && !error ? <Empty text="No kiosk orders are awaiting payment." /> : null}</aside>; }
function QueuePanel({ orders, error, now, onOpen, onView }: { orders: Order[]; error?: string; now: number; onOpen: (order: Order) => void; onView: () => void }) { return <section className="rail-panel"><header><h2><UtensilsCrossed size={17}/>Kitchen Queue</h2><span>{orders.length} Active</span></header>{error ? <AreaError text={error} /> : orders.map((order) => <button className={`queue-row ${order.status}`} key={order.id} onClick={() => onOpen(order)}><span><b>{kitchenLabel(kitchenStage(order) || "pending")}</b><strong>#{order.order_number || order.public_token}</strong><small>{elapsedLabel(order.placed_at, now)} elapsed · {(order.order_items || []).length} items</small></span><ChevronRight size={16}/></button>)}{!orders.length && !error ? <Empty text="No active Kitchen orders." /> : null}<button className="rail-footer" onClick={onView}>View Full Kitchen Queue <ChevronRight size={15}/></button></section>; }
function ReadyPanel({ orders, busy, currency, onHandover }: { orders: Order[]; busy: string; currency: string; onHandover: (order: Order) => void }) { return <section className="rail-panel"><header><h2><Check size={17}/>Ready for Handover</h2><span>{orders.length} Ready</span></header>{orders.slice(0, 3).map((order) => <article className="ready-card" key={order.id}><div><b>READY</b><strong>#{order.order_number || order.public_token}</strong><small>{(order.order_items || []).length} items · {currency}{order.total_amount.toFixed(2)}</small></div><button className="staff-button primary" disabled={!!busy} onClick={() => void onHandover(order)}>Mark Handed Over</button></article>)}{!orders.length && <Empty text="No orders are ready for handover." />}</section>; }
function DeviceAlert({ status }: { status?: string }) { const alert = status === "warning" || status === "issue"; return <section className={`device-alert ${alert ? "has-alert" : ""}`}><AlertTriangle size={17}/><span><b>{alert ? "Device alert" : "No Device Alerts"}</b><small>{alert ? "This device needs attention." : "Counter device is reporting normally."}</small></span></section>; }
function CounterOrdersPage({ orders, pending, error, currency, busy, now, onRefresh, onHandover, selected, onSelect, onPayment }: { orders: Order[]; pending: PendingPaymentRow[]; error?: string; currency: string; busy: string; now: number; onRefresh: () => Promise<void>; onHandover: (order: Order) => void; selected: Order | null; onSelect: (order: Order) => void; onPayment: (row: PendingPaymentRow) => void }) { const [search, setSearch] = useState(""); const visible = orders.filter((order) => String(order.order_number || order.public_token).includes(search) || order.status.includes(search.toLowerCase())); return <section className="counter-table-page"><header className="page-toolbar"><label className="staff-search"><Search size={16}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search orders" /></label><button className="staff-button" onClick={() => void onRefresh()}><RefreshCw size={16}/>Refresh</button></header><div className="counter-orders-layout"><section className="staff-table"><header><span>Order</span><span>Source</span><span>Payment</span><span>Kitchen Status</span><span>Elapsed</span></header>{error ? <AreaError text={error} retry={onRefresh} /> : visible.map((order) => <button key={order.id} onClick={() => onSelect(order)}><span><b>#{order.order_number || order.public_token}</b><small>{order.order_type === "dine_in" ? `Table ${order.table_label || "—"}` : "Takeaway"}</small></span><span>{order.source || "Kiosk"}</span><span>{order.payment_status}</span><span className={`state-pill ${order.status}`}>{order.status}</span><span>{elapsedLabel(order.placed_at, now)}</span></button>)}{!visible.length && !error ? <Empty text="No Kitchen orders match this view." /> : null}</section><aside className="order-detail"><h2>{selected ? `Order #${selected.order_number || selected.public_token}` : "Select an order"}</h2>{selected ? <><p>{selected.source || "Kiosk"} · {selected.payment_status} · {selected.status}</p>{(selected.order_items || []).map((item) => <p key={item.id}>{item.quantity} × {item.product_name}</p>)}<p>Total: {currency}{selected.total_amount.toFixed(2)}</p>{selected.status === "ready" ? <button className="staff-button primary" disabled={!!busy} onClick={() => void onHandover(selected)}>Mark Handed Over</button> : null}</> : <p>View payment, items and Kitchen lifecycle details without taking preparation actions.</p>}<h3>Awaiting payment</h3>{pending.map((row) => <button className="detail-link" key={row.id} onClick={() => onPayment(row)}>#{row.order?.order_number || row.id.slice(0, 8)} <ChevronRight size={15}/></button>)}</aside></div></section>; }
function HistoryPage({ orders, error, currency, now, onRefresh }: { orders: Order[]; error?: string; currency: string; now: number; onRefresh: () => Promise<void> }) { return <section className="counter-table-page"><header className="page-toolbar"><div><h1>Handover History</h1><small>Completed handovers for this Counter device.</small></div><button className="staff-button" onClick={() => void onRefresh()}><RefreshCw size={16}/>Refresh</button></header><section className="staff-table handover-table"><header><span>Order</span><span>Source</span><span>Ready At</span><span>Handed Over</span><span>Kitchen Prep</span></header>{error ? <AreaError text={error} retry={onRefresh} /> : orders.map((order) => <article key={order.id}><span><b>#{order.order_number || order.public_token}</b><small>{currency}{order.total_amount.toFixed(2)}</small></span><span>{order.source || "Kiosk"}</span><span>{order.ready_at ? new Date(order.ready_at).toLocaleTimeString() : "—"}</span><span>{order.completed_at ? new Date(order.completed_at).toLocaleTimeString() : "—"}</span><span>{order.prep_started_at && order.ready_at ? elapsedLabel(order.prep_started_at, new Date(order.ready_at).getTime()) : elapsedLabel(order.placed_at, now)}</span></article>)}{!orders.length && !error ? <Empty text="No handovers have been recorded yet." /> : null}</section></section>; }
function ModifierDialog({ product, selected, currency, onToggle, onClose, onConfirm }: { product: Product; selected: ModifierOption[]; currency: string; onToggle: (option: ModifierOption) => void; onClose: () => void; onConfirm: () => void }) { return <div className="staff-dialog-backdrop"><section className="staff-dialog" role="dialog" aria-modal="true" aria-label={`Configure ${product.name}`}><header><h2>Configure {product.name}</h2><button className="icon-button" onClick={onClose}>×</button></header>{(product.modifier_groups || []).map((group) => <fieldset key={group.id}><legend>{group.name}{group.is_required ? " (required)" : ""}</legend>{group.options.filter((option) => option.is_available).map((option) => <label key={option.id}><input type="checkbox" checked={selected.some((item) => item.id === option.id)} onChange={() => onToggle(option)} />{option.name}<span>{option.price_delta ? `+${currency}${option.price_delta.toFixed(2)}` : ""}</span></label>)}</fieldset>)}<footer><button className="staff-button" onClick={onClose}>Cancel</button><button className="staff-button primary" onClick={onConfirm}>Add to Order</button></footer></section></div>; }
function PaymentDialog({ row, currency, testMode, onClose, onRefresh }: { row: PendingPaymentRow; currency: string; testMode: boolean; onClose: () => void; onRefresh: () => Promise<void> }) { const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const order = row.order || {}; const run = async () => { setBusy(true); try { if (testMode) await api.testRuntimeMarkPaid(row.id); else { if (!row.claim) await api.liveCounterClaimPayment(row.id); await api.liveCounterSessionMarkPaid(row.id, { business_id: String(row.business_id), amount: Number(row.amount || order.total_amount || 0), method: "cash" }); } await onRefresh(); onClose(); } catch (error) { setMessage(error instanceof Error ? error.message : "Payment could not be confirmed."); } finally { setBusy(false); } }; return <div className="staff-dialog-backdrop"><section className="staff-dialog" role="dialog" aria-modal="true" aria-label="Counter payment"><header><h2>Counter payment</h2><button className="icon-button" onClick={onClose}>×</button></header><p><b>Order:</b> #{order.order_number || order.public_token || row.id.slice(0, 8)}</p><p><b>Total:</b> {currency}{Number(row.amount || order.total_amount || 0).toFixed(2)}</p><p className="info-panel">This order will reach Kitchen only after this authoritative payment confirmation.</p>{message && <p className="staff-notice">{message}</p>}<footer><button className="staff-button" onClick={onClose}>Close</button><button className="staff-button primary" disabled={busy} onClick={() => void run()}>{busy ? "Confirming…" : row.claim ? "Take payment" : "Claim & take payment"}</button></footer></section></div>; }
function AreaError({ text, retry }: { text: string; retry?: () => void | Promise<void> }) { return <div className="area-error"><p>{text}</p>{retry ? <button className="staff-button" onClick={() => void retry()}>Retry</button> : null}</div>; }
function Empty({ text }: { text: string }) { return <p className="staff-empty">{text}</p>; }
